language: cpp
sudo: required
dist: trusty

compiler:
  - clang
  - gcc

install:
  - sudo apt-get install -qq cmake
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++" CC="gcc"; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -qq clang; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++"; fi
  - sudo apt-get install -qq libsdl2-dev
  - sudo apt-get install -qq libc++-dev

before_script: cmake CMakeLists.txt

script:
  - $CXX --version
  - make
